hydra:
  run:
    dir: ../test_results/${now:%Y-%m-%d}/${now:%H-%M-%S}
seed: 3
debug: False
gpu: 3
checkpoint_resume_path: '/wdata/roironen/Deploy/VIPCT/outputs/2022-04-09_AirMSPI_BOMEX_Res50_FPN_64_channels_Sampl_6_18_9cams_L2_relative_LR5.0e-05_query_200_ext_div10/17-07-20/checkpoints/cp_50000.pth'
data:
  dataset_name: 'AirMSPI'
#  image_size: [261, 261] # [height, width]
  n_val: -1
#backbone:
#  sampling_support: 3
#  sampling_output_size: 3
ct_net:
  val_n_query: 500
  val_mask_type: 'space_carving' # 'gt_mask' #'space_carving'  #'space_carving' 'gt_mask' None
  query_point_val_method: 'topk'

min_mask_points: 0
#backbone:
#  out_channels:
#  n_sampling_nets: 1
