hydra:
  run:
    dir: ../test_results/${now:%Y-%m-%d}/${now:%H-%M-%S}
seed: 3
debug: False
gpu: 3
#checkpoint_resume_path: '/wdata/roironen/Deploy/VIPCT/outputs/2022-05-29_AirMSPIv2_varying_BOMEX_Res50_FPN_64_channels_Sampl_6_18_9cams_L2_relative_LR5.0e-05_query_150_ext_div10/16-58-26/checkpoints/cp_45000.pth'
#checkpoint_resume_path: '/wdata/roironen/Deploy/VIPCT/outputs/2022-05-29_AirMSPIv2_varying_BOMEX_Res50_FPN_64_channels_Sampl_6_18_9cams_L2_relative_LR5.0e-05_query_150_ext_div10_NOIMG2/17-07-02/checkpoints/cp_70000.pth'
checkpoint_resume_path: '/wdata/roironen/Deploy/VIPCT/outputs/2022-05-31_AirMSPIv2_varying_BOMEX_Res50_FPN_64_channels_Sampl_6_18_9cams_L2_relative_LR5.0e-05_query_150_ext_div10_NOIMG7/07-02-46/checkpoints/cp_70000.pth'
data:
  dataset_name: 'AirMSPI'
#  image_size: [261, 261] # [height, width]
  n_val: -1
#backbone:
#  sampling_support: 3
#  sampling_output_size: 3
ct_net:
  val_n_query: 100
  val_mask_type: 'space_carving' # 'gt_mask' #'space_carving'  #'space_carving' 'gt_mask' None
  query_point_val_method: 'all'

min_mask_points: 0
#backbone:
#  out_channels:
#  n_sampling_nets: 1
