hydra:
  run:
    dir: ../test_results/${now:%Y-%m-%d}/${now:%H-%M-%S}
seed: 3
debug: False
gpu: 3
checkpoint_resume_path: '/wdata/roironen/Deploy/VIPCT/outputs/2022-03-26_BOMEX_Res50_FPN_512channels_Sampl_5_modify_first_layer_T_10cams_L2_LR00005_FixCTv3_wd00001_n_sampling_nets10/22-31-28/checkpoints/cp_145000.pth'
data:
  dataset_name: 'BOMEX_10cams'
#  image_size: [261, 261] # [height, width]
  n_val: -1
#backbone:
#  sampling_support: 3
#  sampling_output_size: 3
ct_net:
  val_n_query: 2000
  val_mask_type: 'space_carving' # 'gt_mask' #'space_carving'  #'space_carving' 'gt_mask' None
  query_point_val_method: 'all'

#backbone:
#  out_channels:
#  n_sampling_nets: 1
