hydra:
  run:
    dir: ../outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
seed: 3
debug: False
resume: False
stats_print_interval: 25
validation_iter_interval: 2000
checkpoint_epoch_interval: 10
checkpoint_resume_path: 'outputs/2022-03-13/23-49-07/checkpoints/cp_410.pth'
data:
  dataset_name: 'satellites_images'
  image_size: [261, 261] # [height, width]
  n_training: 50
  n_val: 20
  n_cam: 10
  rand_cam: True
optimizer:
  max_epochs: 1000
  lr: 0.00005
  batch_size: 4
  iter_steps: [50000, 75000]
  lr_scheduler_gamma: 0.1
visualization:
  history_size: 10
  visdom: False
  visdom_server: 'localhost'
  visdom_port: 8097
  visdom_env: 'nerf_pytorch3d'
ct_net:
  n_harmonic_functions_xyz: 3 #10
  n_harmonic_functions_dir: 2 #4
  n_hidden_neurons_xyz: 64
  n_hidden_neurons_dir: 64
  n_layers_xyz: 0
  n_layers_dir: 2
  append_xyz: [2]
  append_dir: [2]
  n_query: 200
  val_n_query: 200
  stop_encoder_grad: False
  dir_at_camera_coordinates: True
  norm_dir: False
  mask_type: 'gt_mask'  #'space_carving' 'gt_mask' None
  val_mask_type: 'gt_mask' #'space_carving'  #'space_carving' 'gt_mask' None
  query_point_method: 'random' #'topk'
  query_point_val_method: 'all'
backbone:
  name: 'resnet34' #'resnet34'
  pretrained: False
  num_layers: 4
  index_interp: 'bilinear'
  index_padding: 'zeros' #'zeros', 'border', or 'reflection'
  upsample_interp: 'bilinear'
  feature_scale: 1.0
  use_first_pool: 'batch'
  sampling_support: 5
decoder:
  name: 'VIPCT' #'FixCT'
  feature_flatten: False
