hydra:
  run:
    dir: ../outputs/${now:%Y-%m-%d}_CASS_Res50_FPN_512channels_Sampl_3_9_10cams_L2_relative_LR5.0e-06_FixCT_wd1.0e-05_n_sampling_nets10_FINETUNEcp_130000/${now:%H-%M-%S}
#    dir: ../outputs/${now:%Y-%m-%d}_tmp/${now:%H-%M-%S}
seed: 3
debug: False
resume: True
stats_print_interval: 25
validation_iter_interval: 2500
checkpoint_iteration_interval: 5000
checkpoint_resume_path: '/wdata/roironen/Deploy/VIPCT/outputs/2022-03-31_BOMEX_Res50_FPN_512channels_Sampl_3_9_10cams_L2_relative_LR5.0e-05_FixCTv4_wd1.0e-05_n_sampling_nets10/00-36-48/checkpoints/cp_130000.pth'
gpu: 0
data:
  dataset_name: 'CASS_10cams' # 'satellites_images' CASS_10cams
#  image_size: [116, 116] # [height, width]
  n_training: -1
  n_val: 40
  n_cam: 10
  rand_cam: False
  mean: 0.017
  std: 0.0072
optimizer:
  max_epochs: 100000
  lr: 5.0e-06
  wd: 1.0e-05
  batch_size: 1
  iter_steps: [120000, 300000]
  lr_scheduler_gamma: 0.1
  loss: 'L2_relative_error' #'L1_relative_error'
ct_net:
  n_harmonic_functions_xyz: 3 #10
  n_harmonic_functions_dir: 2 #4
  n_hidden_neurons_xyz: 64
  n_hidden_neurons_dir: 64
  n_layers_xyz: 4
  n_layers_dir: 2
  append_xyz: [2]
  append_dir: [2]
  n_query: 400
  val_n_query: 200
  stop_encoder_grad: False
  dir_at_camera_coordinates: True
  norm_dir: False
  mask_type: 'space_carving'  #'space_carving' 'gt_mask' None
  val_mask_type: 'space_carving' #'space_carving'  #'space_carving' 'gt_mask' None
  query_point_method: 'random' #'topk'
  query_point_val_method: 'all'
  feature_encoding: False
  use_neighbours: False
backbone:
  name: 'resnet50_fpn' #'resnet34' fasterrcnn_resnet50_fpn
  pretrained: False
  num_layers: 4
  index_interp: 'bilinear'
  index_padding: 'zeros' #'zeros', 'border', or 'reflection'
  upsample_interp: 'bilinear'
  feature_scale: 1.0
  use_first_pool: 'batch'
  sampling_support: 3
  sampling_output_size: 9
  out_channels: 512
  n_sampling_nets: 10
  feature_flatten: False
  modify_first_layer: True
decoder:
  name: 'FixCTv4' #'VIPCT' #'FixCT'
  average_cams: False
  feature_flatten: True
feature_encoder:
  n_harm: 3