hydra:
  run:
    dir: ../test_results/${now:%Y-%m-%d}/${now:%H-%M-%S}
seed: 3
debug: False
checkpoint_resume_path: 'outputs/2022-03-14/12-32-17/checkpoints/cp_120.pth'
data:
  dataset_name: 'clouds'
  image_size: [261, 261] # [height, width]
  n_val: -1
visualization:
  history_size: 10
  visdom: False
  visdom_server: 'localhost'
  visdom_port: 8097
  visdom_env: 'nerf_pytorch3d'
ct_net:
  val_n_query: 350
  val_mask_type: 'space_carving' # 'gt_mask' #'space_carving'  #'space_carving' 'gt_mask' None
  query_point_val_method: 'all'

