hydra:
  run:
    dir: ../test_results/${now:%Y-%m-%d}/${now:%H-%M-%S}
seed: 3
debug: False
checkpoint_resume_path: 'outputs/2022-03-22_BOMEX_Res50_FPN_Sampl_3_modify_first_layer_T/19-36-18/checkpoints/cp_30.pth'
data:
  dataset_name: 'BOMEX_10cams'
  image_size: [261, 261] # [height, width]
  n_val: -1
backbone:
  sampling_support: 3
  sampling_output_size: 3
ct_net:
  val_n_query: 350
  val_mask_type: 'gt_mask' # 'gt_mask' #'space_carving'  #'space_carving' 'gt_mask' None
  query_point_val_method: 'all'

