hydra:
  run:
    dir: /wdata/inbalkom/NN_test_outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
seed: 3
debug: False
gpu: 0
save_results: False
show: True
checkpoint_resume_path: '/home/inbalkom/outputs/2023-02-16/19-08-03/checkpoints/cp_290000.pth'
  # '/wdata/inbalkom/NN_outputs/2023-02-27/19-02-27/checkpoints/cp_310000.pth' '/wdata/inbalkom/NN_outputs/2023-02-27/18-06-35/checkpoints/cp_310000.pth' '/wdata/inbalkom/NN_outputs/2023-02-27/18-26-03/checkpoints/cp_380000.pth' # '/home/inbalkom/outputs/2023-02-16/19-08-03/checkpoints/cp_290000.pth'
data:
  dataset_name: 'BOMEX_10cams_20m_polarization' # 'BOMEX_10cams_20m_polarization' 'BOMEX_50CCN' 'CASS_10cams_20m_polarization'
  n_val: -1
  n_cam: 20

ct_net:
  val_n_query: 500
  val_mask_type: 'space_carving' # 'space_carving' 'gt_mask' None
  query_point_val_method: 'all'

min_mask_points: 30 # 30 for CASS_10cams_50m

