hydra:
  run:
    dir: /wdata/inbalkom/NN_outputs/AirMSPI/${now:%Y-%m-%d}/${now:%H-%M-%S}
comment: 'a'
seed: 3
debug: False
resume: False
stats_print_interval: 25
validation_iter_interval: 2500000000
checkpoint_iteration_interval: 5000
checkpoint_resume_path: ''
gpu: 0
data:
  dataset_name: 'BOMEX_aux_9cams_polarization'
  n_training: -1
  n_val: 40
  n_cam: 8
  drop_index: 1 #7
  rand_cam: False
  mean: [ 0.02262857,  0.0013047,  -0.00013644] # !!!!!!!!!!!!
  std: [0.00207038, 0.00086004, 0.00535393] # !!!!!!!!!!!!
optimizer:
  max_epochs: 100000
  lr: 1.0e-05 # 5.0e-05
  wd: 1.0e-05
  batch_size: 1
  iter_steps: [1000000000] #[120000, 300000]
  lr_scheduler_gamma: 0.1
  lwc_loss:  'L2_relative_error_w_score' # 'L2_relative_error'
ct_net:
  n_hidden_neurons_xyz: 64
  n_hidden_neurons_dir: 64
  n_layers_xyz: 4
  n_layers_dir: 4
  append_xyz: [2]
  append_dir: [2]
  n_query: 150
  val_n_query: 50
  stop_encoder_grad: False
  mask_type: 'space_carving'  #'space_carving' 'gt_mask' None
  val_mask_type: 'space_carving' #'space_carving'  #'space_carving' 'gt_mask' None
  query_point_method: 'random' #'topk'
  query_point_val_method: 'all'
  use_neighbours: False
backbone:
  name: 'resnet34' #'resnet50_fpn' #'resnet34' fasterrcnn_resnet50_fpn
  pretrained: False
  num_layers: 4
  index_interp: 'bilinear'
  index_padding: 'zeros' #'zeros', 'border', or 'reflection'
  upsample_interp: 'bilinear'
  feature_scale: 1.0
  use_first_pool: 'batch'
  sampling_support: 6
  sampling_output_size: 18
  in_channels: 3
  out_channels: 64
  n_sampling_nets: 8
  feature_flatten: False
  modify_first_layer: True
decoder:
  name: 'FixCTv4_microphysics_seperated_w_score'
  average_cams: False
  feature_flatten: True
