hydra:
  run:
    dir: /wdata/inbalkom/NN_outputs/AirMSPI/test_results/${now:%Y-%m-%d}/${now:%H-%M-%S}
seed: 3
debug: False
gpu: 0
checkpoint_resume_path: '/wdata/inbalkom/NN_outputs/AirMSPI/2023-02-27/18-34-44/checkpoints/cp_160000.pth'
data:
  dataset_name: '6065_BOMEX_for_test' #'6065_BOMEX_for_test' #'32N123W_experiment_cloud1'
  n_val: -1

ct_net:
  val_n_query: 100
  val_mask_type: 'space_carving' # 'space_carving' 'gt_mask' None
  query_point_val_method: 'all'

min_mask_points: 0

