hydra:
  run:
    dir: ../test_results/${now:%Y-%m-%d}/${now:%H-%M-%S}
seed: 3
debug: False
gpu: 0
save_results: False
show: False
checkpoint_resume_path: '/wdata/roironen/Deploy/VIPCT/outputs/2022-04-04_BOMEX_Res50_FPN_512channels_Sampl_3_9_10cams_L2_relative_LR5.0e-05_FixCT_wd1.0e-05_n_sampling_nets10_50m/16-47-25/checkpoints/cp_155000.pth'
data:
  dataset_name: 'BOMEX_10cams'
  n_val: -1

ct_net:
  val_n_query: 500
  val_mask_type: 'space_carving' # 'gt_mask' #'space_carving'  #'space_carving' 'gt_mask' None
  query_point_val_method: 'all'

min_mask_points: 0
#backbone:
#  out_channels:
#  n_sampling_nets: 1
