hydra:
  run:
    dir: ../test_results/${now:%Y-%m-%d}/${now:%H-%M-%S}
seed: 3
debug: False
gpu: 0
save_results: False
show: False
checkpoint_resume_path: '/wdata/roironen/VIP-CT_models/CASS/10cams/20m/vip-ct.pth'
data:
  dataset_name: 'BOMEX_10cams_20m'
  n_val: -1

ct_net:
  val_n_query: 500
  val_mask_type: 'space_carving' # 'space_carving' 'gt_mask' None
  query_point_val_method: 'all'

min_mask_points: 0 # 30 for CASS_10cams_50m

