defaults:
  - _self_
  - baselinev2

hydra:
  run:
    dir: ../outputs/${now:%Y-%m-%d}_Train_BOMEX500_V2_EMD_lr_5.0e-04/${now:%H-%M-%S}
#    dir: ../outputs/${now:%Y-%m-%d}_Tmp/${now:%H-%M-%S}

resume: True
stats_print_interval: 25
validation_iter_interval: 2500
checkpoint_iteration_interval: 5000
checkpoint_resume_path: '/wdata/roironen/Deploy/VIPCT/outputs/2023-05-15_Train_BOMEX500_V2_EMD_noise/11-47-40/checkpoints/cp_170000.pth'

gpu: 0
#ALL_DATASETS = ("Toy_10cameras_20m","Toy2_10cameras_20m","BOMEX_CASS_10cameras_20m", "CASS_10cameras_20m", "CASS_10cameras_50m", "BOMEX_10cameras_20m",''
#                "BOMEX_10cameras_50m", "BOMEX_32cameras_20m", "BOMEX_32cameras_50m", "BOMEX_10cameras_20m_varying_S", "BOMEX_10cameras_20m_varying_M",
#                "BOMEX_10cameras_20m_varying_L", "BOMEX_10cameras_20m_varying_XL",
#                "subset_of_seven_clouds",
#                "BOMEX_50CCN_10cameras_20m",
#                "BOMEX_50CCN_aux_10cameras_20m",
#                'CASS_600CCN_roiprocess_10cameras_20m',
#                "HAWAII_2000CCN_10cameras_20m",
#                "DYCOMS_RF02_500CCN_10cameras_20m",
#                "DYCOMS_RF02_50CCN_10cameras_20m",
#                )
data:
  dataset_name: BOMEX_10cameras_20m #['CASS_600CCN_roiprocess_10cameras_20m','HAWAII_2000CCN_10cameras_20m','BOMEX_50CCN_10cameras_20m','BOMEX_10cameras_20m']
  #['CASS_600CCN_roiprocess_10cameras_20m','HAWAII_2000CCN_10cameras_20m','BOMEX_50CCN_10cameras_20m','BOMEX_10cameras_20m'] #'CASS_600CCN_roiprocess_10cameras_20m'
  n_training: -1
  n_val: 40
  noise: True


optimizer:
  lr: 5.0e-04
  wd: 1.0e-05
  loss: 'EMD' #'L2_relative_error' # 'CE'
  ce_weight_zero: True

cross_entropy:
  min: 0
  max: 300
  bins: 301
  smoothing_std: 2

decoder:
  name: 'FixCTv4_CE' #'CE' #FixCTv4_CE
