hydra:
  run:
    dir: ../test_results/${now:%Y-%m-%d}/${now:%H-%M-%S}
seed: 0
debug: False
gpu: 0
save_results: True
show: False
#checkpoint_resume_path: '/wdata/roironen/Deploy/VIPCT/outputs/2023-02-26_VIPCTv2_BOMEX_Res50_FPN_512channels_Sampl_3_9_10cams_CE_300bins_LR5.0e-05_Gcam_64_Gdomain_64_maskSC/16-46-37/checkpoints/cp_165000.pth'
#checkpoint_resume_path: '/wdata/roironen/Deploy/VIPCT/outputs/2022-03-31_BOMEX_Res50_FPN_512channels_Sampl_3_9_10cams_L2_relative_LR5.0e-05_FixCTv4_wd1.0e-05_n_sampling_nets10/00-36-48/checkpoints/cp_130000.pth'
checkpoint_resume_path: '/wdata/roironen/Deploy/VIPCT/outputs/2023-03-25_FT_BOMEX_50CCN_10cameras_20m_trainset_all_sc_mask_V1/22-12-28/checkpoints/cp_300.pth'
#checkpoint_resume_path: '/wdata/roironen/Deploy/VIPCT/outputs/2023-03-25_FT_BOMEX_50CCN_10cameras_20m_trainset_all_sc_mask_differentiable_maxV2/21-43-43/checkpoints/cp_350.pth'
data:
  dataset_name: 'BOMEX_50CCN_10cameras_20m'
#  dataset_name: 'CASS_600CCN_roiprocess_10cameras_20m'
#  dataset_name: 'HAWAII_2000CCN_10cameras_20m'
#  dataset_name: 'DYCOMS_RF02_500CCN_10cameras_20m'
#  dataset_name: 'DYCOMS_RF02_50CCN_10cameras_20m'
#  dataset_name: 'BOMEX_50CCN_aux_10cameras_20m'
  n_val: -1

ct_net:
  val_n_query: 500
  val_mask_type: 'space_carving' # 'space_carving' 'gt_mask' None
  query_point_val_method: 'all'
  pred_type: 'max' #max
  conf_type: 'prob' #conf_interval prob std rel_prob
min_mask_points: 0 # 30 for CASS_10cams_50m
decoder:
  type: 'mlp' #mlp transformer

optimizer:
  loss: 'CE'
version:
  'V1'