hydra:
  run:
    dir: ../outputs/${now:%Y-%m-%d}_FT_BOMEX50CCN_BOMEX_50CCN_10cameras_20m_V1_LR5.0e-06_EVALadded/${now:%H-%M-%S}
seed: 0
debug: False
resume: True

version: 'V2'
stats_print_interval: 10
validation_iter_interval: 10
checkpoint_iteration_interval: 25
#checkpoint_resume_path: '/wdata/roironen/Deploy/VIPCT/outputs/2023-04-05_BOMEX_500CCN_10cameras_20m_V1_noise/14-16-49/checkpoints/cp_230000.pth'
checkpoint_resume_path: '/wdata/roironen/Deploy/VIPCT/outputs/2023-04-05_BOMEX_50CCN_10cameras_20m_V1_noise/14-15-58/checkpoints/cp_225000.pth'
#checkpoint_resume_path: '/wdata/roironen/Deploy/VIPCT/outputs/2022-03-31_BOMEX_Res50_FPN_512channels_Sampl_3_9_10cams_L2_relative_LR5.0e-05_FixCTv4_wd1.0e-05_n_sampling_nets10/00-36-48/checkpoints/cp_130000.pth'
#checkpoint_resume_path: '/wdata/roironen/Deploy/VIPCT/outputs/2023-03-25_FT_BOMEX_50CCN_10cameras_20m_trainset_all_sc_mask_differentiable_maxV2/21-43-43/checkpoints/cp_350.pth'
gpu: 3
data:
  dataset_name: 'BOMEX_50CCN_10cameras_20m' #'BOMEX_50CCN_10cameras_20m' #'CASS_600CCN_roiprocess_10cameras_20m'
  n_training: -1
  n_val: 60
  n_cam: 10
  rand_cam: False
  mean: 0.017
  std: 0.0072
  noise: True

optimizer:
  max_epochs: 100000
  lr: 5.0e-06
  wd: 1.0e-05
  batch_size: 1
  iter_steps: [1000000000]
  lr_scheduler_gamma: 0.1
  ce_weight_zero: True
  loss: 'L2' #'L2_relative_error' # 'CE'


cross_entropy:
  min: 0
  max: 300
  bins: 301
ct_net:
  n_hidden_neurons_xyz: 64
  n_hidden_neurons_dir: 64
  n_layers_xyz: 4
  n_layers_dir: 4
  append_xyz: [2]
  append_dir: [2]
  n_query: 200
  val_n_query: 200
  stop_encoder_grad: True
  mask_type: 'space_carving'  #'space_carving' 'gt_mask' None
  val_mask_type: 'space_carving' #'space_carving'  #'space_carving' 'gt_mask' None
  query_point_method: 'all' #'topk' gt_sc_random
  decoder_batchify: True
  query_point_val_method: 'all'
  use_neighbours: False # penalize model also for voxel neighbours
  pred_type: 'differentiable_max' #'differentiable_max'
  conf_type: 'prob' #conf_interval prob std rel_prob

backbone:
  name: 'resnet50_fpn' #'resnet34' fasterrcnn_resnet50_fpn
  pretrained: False
  num_layers: 4
  index_interp: 'bilinear'
  index_padding: 'zeros' #'zeros', 'border', or 'reflection'
  upsample_interp: 'bilinear'
  feature_scale: 1.0
  use_first_pool: 'batch'
  sampling_support: 3
  sampling_output_size: 9
  out_channels: 512
  n_sampling_nets: 10
  feature_flatten: False
  modify_first_layer: True

decoder:
  name: 'FixCTv4' #'CE' #FixCTv4_CE
  type: 'mlp' #mlp transformer
  masked: False
  num_masked: 20
  average_cams: False
  feature_flatten: True

shdom:
  n_jobs: 35
  use_forward_grid: True
  add_rayleigh: True

