defaults:
  - baselinev2
  - _self_

hydra:
  run:
    dir: ../outputs/${now:%Y-%m-%d}_Train_TOY3_3views/${now:%H-%M-%S}
#    dir: ../outputs/${now:%Y-%m-%d}_Tmp/${now:%H-%M-%S}

resume: False
stats_print_interval: 25
validation_iter_interval: 25000000000
checkpoint_iteration_interval: 5000
checkpoint_resume_path: '/wdata/roironen/Deploy/VIPCT/outputs/2023-04-05_BOMEX_50CCN_10cameras_20m_CE_noise/14-15-26/checkpoints/cp_230000.pth'

gpu: 2
#ALL_DATASETS = ("Toy_10cameras_20m","Toy2_10cameras_20m","BOMEX_CASS_10cameras_20m", "CASS_10cameras_20m", "CASS_10cameras_50m", "BOMEX_10cameras_20m",''
#                "BOMEX_10cameras_50m", "BOMEX_32cameras_20m", "BOMEX_32cameras_50m", "BOMEX_10cameras_20m_varying_S", "BOMEX_10cameras_20m_varying_M",
#                "BOMEX_10cameras_20m_varying_L", "BOMEX_10cameras_20m_varying_XL",
#                "subset_of_seven_clouds",
#                "BOMEX_50CCN_10cameras_20m",
#                "BOMEX_50CCN_aux_10cameras_20m",
#                'CASS_600CCN_roiprocess_10cameras_20m',
#                "HAWAII_2000CCN_10cameras_20m",
#                "DYCOMS_RF02_500CCN_10cameras_20m",
#                "DYCOMS_RF02_50CCN_10cameras_20m",
#                )
data:
  dataset_name: Toy3_10cameras_20m #['CASS_600CCN_roiprocess_10cameras_20m','HAWAII_2000CCN_10cameras_20m','BOMEX_50CCN_10cameras_20m','BOMEX_10cameras_20m']
  #['CASS_600CCN_roiprocess_10cameras_20m','HAWAII_2000CCN_10cameras_20m','BOMEX_50CCN_10cameras_20m','BOMEX_10cameras_20m'] #'CASS_600CCN_roiprocess_10cameras_20m'
  n_training: -1
  n_val: 40
  noise: True


optimizer:
  lr: 5.0e-05
  wd: 1.0e-05
  loss: 'CE' #'L2_relative_error' # 'CE'
  ce_weight_zero: True
ct_net:
  mask_type: 'toy3'  #'space_carving' 'gt_mask' None
  val_mask_type: 'toy3' #'space_carving'  #'space_carving' 'gt_mask' None
cross_entropy:
  min: 0
  max: 300
  bins: 301
  smoothing_std: None #2

decoder:
  name: 'FixCTv4_CE' #'CE' #FixCTv4_CE
