hydra:
  run:
    dir: ../test_results/${now:%Y-%m-%d}_BOMEX_500CCN_V2_all/${now:%H-%M-%S}
seed: 0
debug: False
gpu: 1
save_results: False
show: False
mode: eval
#checkpoint_resume_path: '/wdata/roironen/Deploy/VIPCT/outputs/2023-02-26_VIPCTv2_BOMEX_Res50_FPN_512channels_Sampl_3_9_10cams_CE_300bins_LR5.0e-05_Gcam_64_Gdomain_64_maskSC/16-46-37/checkpoints/cp_165000.pth'
#checkpoint_resume_path: '/wdata/roironen/Deploy/VIPCT/outputs/2023-04-05_BOMEX_500CCN_10cameras_20m_V1_noise/14-16-49/checkpoints/cp_230000.pth'
#checkpoint_resume_path: '/wdata/roironen/Deploy/VIPCT/outputs/2023-04-10_FT_BOMEX50CCN_BOMEX_50CCN_10cameras_20m_V1_LR5.0e-06_EVALadded/20-48-35/checkpoints/cp_50.pth'
checkpoint_resume_path: '/wdata/roironen/Deploy/VIPCT/outputs/2023-04-19_Train_BOMEX50_CASS600_10cameras_20m_V2_noise/16-25-59/checkpoints/cp_140000.pth'
#checkpoint_resume_path: '/wdata/roironen/Deploy/VIPCT/outputs/2023-04-19_FT_BOMEX500_Train_BOMEX500_v2/10-10-37/checkpoints/cp_500.pth'
data:
  dataset_name: 'BOMEX_10cameras_20m'
#  dataset_name: 'Toy2_10cameras_20m'
#  dataset_name: 'BOMEX_50CCN_10cameras_20m'
#  dataset_name: 'CASS_600CCN_roiprocess_10cameras_20m'
#  dataset_name: 'HAWAII_2000CCN_10cameras_20m'
#  dataset_name: 'DYCOMS_RF02_500CCN_10cameras_20m'
#  dataset_name: 'DYCOMS_RF02_50CCN_10cameras_20m'
#  dataset_name: 'BOMEX_50CCN_aux_10cameras_20m'
  n_val: -1
  noise: True

ct_net:
  val_n_query: 500
  val_mask_type: 'space_carving' # 'space_carving' 'gt_mask' None
  query_point_val_method: 'all'
  pred_type: 'differentiable_max_correct' #max
  conf_type: 'prob' #conf_interval prob std rel_prob
  decoder_batchify: True

min_mask_points: 0 # 30 for CASS_10cams_50m
decoder:
  type: 'mlp' #mlp transformer

version:
  'V2'