defaults:
  - baselinev2
  - _self_

hydra:
  run:
    dir: ../outputs/${now:%Y-%m-%d}_BOMEX_5000CCN_10cameras_20m_V1_noise_TRUE_full_well_val_None_lr_5.0e-05_Enc_SwinTransformer/${now:%H-%M-%S}
#    dir: ../outputs/${now:%Y-%m-%d}_Tmp/${now:%H-%M-%S}
#
resume: False
stats_print_interval: 25
validation_iter_interval: 2500
checkpoint_iteration_interval: 5000
#checkpoint_resume_path: '/wdata/roironen/Deploy/VIPCT/outputs/2023-07-16_FT_BOMEX50_Train=BOMEX50_v2_mode_train_lr5.0e-05train_lora/18-12-46/checkpoints/cp_60.pth'
#checkpoint_resume_path: '/wdata/roironen/Deploy/VIPCT/VIPCT/outputs/2023-07-18_PSEUDO_BOMEX_50CCN_10cameras_20m_CE_noise_TRUE_full_well_val_None_CE_weight_zero_1_lr_1.0e-05_after_LoRA/12-30-30/checkpoints/cp_5000.pth'
gpu: 1
#ALL_DATASETS = ("Toy_10cameras_20m","Toy2_10cameras_20m","BOMEX_CASS_10cameras_20m", "CASS_10cameras_20m", "CASS_10cameras_50m", "BOMEX_10cameras_20m",''
#                "BOMEX_10cameras_50m", "BOMEX_32cameras_20m", "BOMEX_32cameras_50m", "BOMEX_10cameras_20m_varying_S", "BOMEX_10cameras_20m_varying_M",
#                "BOMEX_10cameras_20m_varying_L", "BOMEX_10cameras_20m_varying_XL",
#                "subset_of_seven_clouds",
#                "BOMEX_50CCN_10cameras_20m",
#                "BOMEX_50CCN_aux_10cameras_20m",
#                'CASS_600CCN_roiprocess_10cameras_20m',
#                "HAWAII_2000CCN_10cameras_20m",
#                "DYCOMS_RF02_500CCN_10cameras_20m",
#                "DYCOMS_RF02_50CCN_10cameras_20m",
#                )
data:
  dataset_name: BOMEX_5000CCN_new_10cameras_20m #['CASS_600CCN_roiprocess_10cameras_20m','HAWAII_2000CCN_10cameras_20m','BOMEX_50CCN_10cameras_20m','BOMEX_10cameras_20m']
  #['CASS_600CCN_roiprocess_10cameras_20m','HAWAII_2000CCN_10cameras_20m','BOMEX_50CCN_10cameras_20m','BOMEX_10cameras_20m'] #'CASS_600CCN_roiprocess_10cameras_20m'
  n_training: -1
  n_val: 40
  noise: True

optimizer:
  lr: 5.0e-05
  wd: 1.0e-05
  loss: 'L2_relative_error' #'L2_relative_error' # 'CE'
  ce_weight_zero: True
  BBSE_ratio: False
  CE_weight_zero: 0.01

ct_net:
  n_query: 500
#  stop_encoder_grad: False
#  pred_type: 'differentiable_max'
#  prob_gain: 10
#  conf_type: 'entropy' #conf_interval prob std rel_prob
  encoder_mode: 'train'

backbone:
  name: 'swin_v2_b' #'resnet50_fpn' 'resnet34' fasterrcnn_resnet50_fpn


#  mask_type: 'toy3'  #'space_carving' 'gt_mask' None
#  val_mask_type: 'toy3' #'space_carving'  #'space_carving' 'gt_mask' None

cross_entropy:
  min: 0
  max: 300
  bins: 301

decoder:
  name: 'FixCTv4' #'CE' #FixCTv4_CE
#  apply_lora: True
#  lora_dim: 64
#  lora_alpha: 1000
#  lora_dropout: 0
#  fan_in_fan_out: False
#  merge_weights: False
